GET  http://localhost:3003/api/blogs
###

POST  http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYyMzM3ZTEwNTMzYTZkYWVmODUxNWY3OSIsImlhdCI6MTY0NzYyNjE2MCwiZXhwIjoxNjQ3NjI5NzYwfQ.uAEsw9jwGiRBf-_j2cAixxYUqWrq4oGQ1SSeKcWHvm0

{
    "title": "Test Blog",
    "author": "Simon V.S.",
    "url": "test-blog",
    "likes": 7
}
###
POST  http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "admin",
    "name": "Admin",
    "password": "password"
}

###
PUT http://localhost:3003/api/blogs/6234c81736d048e129037011
Content-Type: application/application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYyMzM3ZTEwNTMzYTZkYWVmODUxNWY3OSIsImlhdCI6MTY0NzYyNjE2MCwiZXhwIjoxNjQ3NjI5NzYwfQ.uAEsw9jwGiRBf-_j2cAixxYUqWrq4oGQ1SSeKcWHvm0

{
    "user": "62337e10533a6daef8515f79",
    "title": "Test Blog 3",
    "author": "Simon V.S.",
    "url": "test-blog-3",
    "likes": 8
}

###

POST  http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYyMzRkNDcxMmYwODUxZDM4NTY4Y2UxOSIsImlhdCI6MTY0NzYzMDMwMywiZXhwIjoxNjQ3NjMzOTAzfQ.99ve1vLn2uc12ryrUBGbYh5nIdUakjo3rlJuNlala3w

{
    "title": "Test Blog 3",
    "author": "Simon V.S.",
    "url": "test-blog-3",
    "likes": 7
}

###
DELETE http://localhost:3003/api/blogs/6234d5e2e9368f9d7c02fce3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYyMzRkNDcxMmYwODUxZDM4NTY4Y2UxOSIsImlhdCI6MTY0NzYzMDMwMywiZXhwIjoxNjQ3NjMzOTAzfQ.99ve1vLn2uc12ryrUBGbYh5nIdUakjo3rlJuNlala3w
